### ISSUE TITLE
'Player x wins' Alert before square is drawn

### ISSUE THREAD

**Issue by devbyjonah** [khanhtranngoccva/TicTacToeAdvanced#1]
Hey Khanh! I was checking out the project and noticed that when a player wins the game, the alert appears before the final 'X' or 'O' actually gets drawn. It would be a good improvement to draw the character into the square before or at the same time as the alert. I need practice opening and closing issues/pull requests so I thought this would be a good issue to tackle.

**Comment by khanhtranngoccva** [comment]
Fixed with last pull request.
